FROM runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip
RUN pip install -e .
RUN pip install -r requirements-serverless.txt
RUN python scripts/download_weights.py --weights-dir /app/weights

ENV LD_LIBRARY_PATH=/usr/local/lib/python3.11/dist-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH
ENV WEIGHTS_DIR=/app/weights

CMD ["python", "-u", "handler.py"]
